/* GENERATED by tools/build_data.py from the mit4mit exports. Do not edit by hand. */
var SEATING_RAW = {
 "groups": {
  "חברים כלה": {
   "he": "חברים כלה",
   "ar": "أصدقاء العروس",
   "en": "Bride's friends"
  },
  "מוזמני הורי הכלה": {
   "he": "מוזמני הורי הכלה",
   "ar": "ضيوف أهل العروس",
   "en": "Bride's parents' guests"
  },
  "משפחת הכלה": {
   "he": "משפחת הכלה",
   "ar": "عائلة العروس",
   "en": "Bride's family"
  },
  "מוזמני הורי החתן": {
   "he": "מוזמני הורי החתן",
   "ar": "ضيوف أهل العريس",
   "en": "Groom's parents' guests"
  },
  "חברים חתן": {
   "he": "חברים חתן",
   "ar": "أصدقاء العريس",
   "en": "Groom's friends"
  },
  "חתן עבודה": {
   "he": "חתן - עבודה",
   "ar": "زملاء عمل العريس",
   "en": "Groom's work"
  }
 },
 "sides": {
  "Carla": {
   "he": "קרלה",
   "ar": "كارلا",
   "en": "Carla"
  },
  "Charlie": {
   "he": "צ'רלי",
   "ar": "تشارلي",
   "en": "Charlie"
  }
 },
 "tablesInFile": [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30
 ],
 "guests": [
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אדיב עוביד",
    "اديب عبيد",
    "Adib Obeid"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אסעד עוביד )אדיב)",
    "اسعد عبيد (اديب)",
    "Asaad Obeid (Adib)"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "בסאם סלאמה",
    "بسام سلامة",
    "Bassam Salameh"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "נביל ימין",
    "نبيل يمين",
    "Nabil Yamin"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "האני עוביד",
    "هاني عبيد",
    "Hani Obeid"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "רוסתום עביד",
    "رستم عبيد",
    "Rostom Obeid"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "פואד עביד",
    "فؤاد عبيد",
    "Fouad Obeid"
   ]
  },
  {
   "table": 1,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אוסאמה חורי",
    "اسامة خوري",
    "Osama Khoury"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "ד אסעד חורי",
    "د. اسعد خوري",
    "Dr. Asaad Khoury"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "נאסר שקור",
    "ناصر شكور",
    "Nasser Shakour"
   ]
  },
  {
   "table": 1,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "איא",
    "اية",
    "Aya"
   ]
  },
  {
   "table": 1,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "אלא עדוי",
    "الاء عدوي",
    "Alaa Adawi"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "סאלי נגאר",
    "سالي نجار",
    "Sally Najjar"
   ]
  },
  {
   "table": 1,
   "count": 2,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "מרוא נסאר",
    "مروة نصار",
    "Marwa Nassar"
   ]
  },
  {
   "table": 2,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مجيد جورج سروع",
    "מג'יד ג'ורג' סרוע",
    "Majid George Sarou"
   ]
  },
  {
   "table": 2,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مارون جورج سروع",
    "מארון ג'ורג' סרוע",
    "Maroun George Sarou"
   ]
  },
  {
   "table": 2,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "شكرالله سروع",
    "שוכראללה סרוע",
    "Shukrallah Sarou"
   ]
  },
  {
   "table": 2,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "امير وهلانه سروع",
    "אמיר והלאנה סרוע",
    "Amir & Hlaneh Sarou"
   ]
  },
  {
   "table": 2,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جاني سروع",
    "ג'אני סרוע",
    "Jani Sarou"
   ]
  },
  {
   "table": 2,
   "count": 4,
   "status": "ok",
   "planned": 4,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جيمي وامل سروع",
    "ג'ימי ואמל סרוע",
    "Jimmy & Amal Sarou"
   ]
  },
  {
   "table": 2,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "نور وميخا عيسى",
    "נור ומיכה עיסא",
    "Nour & Mikha Issa"
   ]
  },
  {
   "table": 2,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "حنا حبيب عيسى",
    "חנא חביב עיסא",
    "Hanna Habib Issa"
   ]
  },
  {
   "table": 2,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "شاكر ابو فارس",
    "שאכר אבו פארס",
    "Shaker Abu Fares"
   ]
  },
  {
   "table": 2,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "نظير سروع",
    "נזיר סרוע",
    "Nazir Sarou"
   ]
  },
  {
   "table": 2,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الياس سروع",
    "אליאס סרוע",
    "Elias Sarou"
   ]
  },
  {
   "table": 3,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "بطرس وفيرا فرحات",
    "בוטרוס ופירה פרחאת",
    "Boutros & Vera Farhat"
   ]
  },
  {
   "table": 3,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مارون يعقوب",
    "מארון יעקוב",
    "Maroun Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "بطرس سعيد عيسى",
    "בוטרוס סעיד עיסא",
    "Boutros Said Issa"
   ]
  },
  {
   "table": 3,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "يامن يعقوب",
    "יאמן יעקוב",
    "Yamen Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ابراهيم سالم",
    "אברהים סאלם",
    "Ibrahim Salem"
   ]
  },
  {
   "table": 3,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اليجرا يعقوب",
    "אליגרה יעקוב",
    "Allegra Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اياد وعبير عيسى",
    "איאד ועביר עיסא",
    "Iyad & Abeer Issa"
   ]
  },
  {
   "table": 3,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مريم يعقوب",
    "מרים יעקוב",
    "Mariam Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "رامي يعقوب",
    "ראמי יעקוב",
    "Rami Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جريس وهناء يعقوب",
    "ג'ריס והנאא יעקוב",
    "Jeries & Hanaa Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "داليا يعقوب",
    "דליה יעקוב",
    "Dalia Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "يوسف ورنده يعقوب",
    "יוסף ורנדה יעקוב",
    "Yousef & Randa Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ماجد وليندا يعقوب",
    "מאג'ד ולינדה יעקוב",
    "Majed & Linda Yacoub"
   ]
  },
  {
   "table": 3,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "رانيا ونسيم روحانا",
    "ראניה ונסים רוחאנא",
    "Rania & Nasim Rouhana",
    "روحانت"
   ]
  },
  {
   "table": 4,
   "count": 5,
   "status": "ok",
   "planned": 5,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ريمون نعمه عيسى",
    "רימון נעמה עיסא",
    "Raymond Neameh Issa"
   ]
  },
  {
   "table": 4,
   "count": 4,
   "status": "ok",
   "planned": 4,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اورلي وويليام عيسى",
    "אורלי וויליאם עיסא",
    "Orly & William Issa"
   ]
  },
  {
   "table": 4,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اميلي زكنون",
    "אמילי זכנון",
    "Emily Zaknoun"
   ]
  },
  {
   "table": 4,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ايلي زكنون",
    "אלי זכנון",
    "Eli Zaknoun"
   ]
  },
  {
   "table": 4,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جوني زكنون",
    "ג'וני זכנון",
    "Johnny Zaknoun"
   ]
  },
  {
   "table": 4,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "حجله مارون",
    "חג'לה מארון",
    "Hajleh Maroun"
   ]
  },
  {
   "table": 4,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جريس مارون",
    "ג'ריס מארון",
    "Jeries Maroun"
   ]
  },
  {
   "table": 4,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "سميره سروع",
    "סמירה סרוע",
    "Samira Sarou"
   ]
  },
  {
   "table": 4,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اورنا وراني خلول",
    "אורנה וראני ח'לול",
    "Orna & Rani Khalloul"
   ]
  },
  {
   "table": 4,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "شربل زكنون",
    "שרבל זכנון",
    "Charbel Zaknoun"
   ]
  },
  {
   "table": 5,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "פיטר שחאדי",
    "بيتر شحادي",
    "Peter Shehadi"
   ]
  },
  {
   "table": 5,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "יוסף אסקנדר",
    "يوسف اسكندر",
    "Yousef Iskandar"
   ]
  },
  {
   "table": 5,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "נרדין ברכאת",
    "نردين بركات",
    "Nardin Barakat"
   ]
  },
  {
   "table": 5,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "בולוס ברכקת",
    "بولس بركات",
    "Boulos Barakat",
    "בולוס ברכאת"
   ]
  },
  {
   "table": 5,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "בשיר ברכאת",
    "بشير بركات",
    "Bashir Barakat"
   ]
  },
  {
   "table": 5,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "בשיר ונאדיה ארמלי/ ברכאת",
    "بشير ونادية ارملي / بركات",
    "Bashir & Nadia Armali / Barakat"
   ]
  },
  {
   "table": 5,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "נאדר ברכאת",
    "نادر بركات",
    "Nader Barakat"
   ]
  },
  {
   "table": 5,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "ריני ברכאת",
    "ريني بركات",
    "Rini Barakat"
   ]
  },
  {
   "table": 5,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "סאמר בנימין",
    "سامر بنيامين",
    "Samer Binyamin"
   ]
  },
  {
   "table": 5,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "חסיב סמיר",
    "حسيب سمير",
    "Hasib Samir"
   ]
  },
  {
   "table": 5,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אליאס ברכאת",
    "الياس بركات",
    "Elias Barakat"
   ]
  },
  {
   "table": 5,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "חנאן חורי",
    "حنان خوري",
    "Hanan Khoury"
   ]
  },
  {
   "table": 6,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "נסים סויד",
    "نسيم سويد",
    "Nasim Sweid"
   ]
  },
  {
   "table": 6,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "מקאריוס עיסא",
    "مكاريوس عيسى",
    "Makarios Issa"
   ]
  },
  {
   "table": 6,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "יוסף סעד",
    "يوسف سعد",
    "Yousef Saad"
   ]
  },
  {
   "table": 6,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "עיסאם סעד",
    "عصام سعد",
    "Issam Saad"
   ]
  },
  {
   "table": 6,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "פואד סעד - עיסאם",
    "فؤاد سعد - عصام",
    "Fouad Saad - Issam"
   ]
  },
  {
   "table": 6,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "טוני ניגם",
    "طوني نجم",
    "Tony Najem"
   ]
  },
  {
   "table": 6,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "פריד שולי",
    "فريد شولي",
    "Farid Shouli"
   ]
  },
  {
   "table": 6,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "שמשום שמשם",
    "شمشوم شمشم",
    "Shamshoum Shamsham"
   ]
  },
  {
   "table": 6,
   "count": 4,
   "status": "ok",
   "planned": 4,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "איליא עבליני",
    "ايليا عبليني",
    "Elia Abelini"
   ]
  },
  {
   "table": 6,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "גוסלין חמאתי",
    "جوسلين حماتي",
    "Josline Hamati"
   ]
  },
  {
   "table": 6,
   "count": 2,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "בשארה חמאתי",
    "بشارة حماتي",
    "Bishara Hamati"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "רוזין קנבורא",
    "روزين قنبورة",
    "Rozeen Kanboura"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "פולינא סאליבא",
    "بولينا صليبا",
    "Polina Saliba"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "גיזיל",
    "جيزيل",
    "Gisele"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "קלוד עאנק",
    "كلود عانق",
    "Claude Aneq"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "מיכא סעדי",
    "ميخا سعدي",
    "Mikha Saadi"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "איה מורא",
    "اية مورا",
    "Aya Moura"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "نبيل حضرج",
    "נביל חדרג'",
    "Nabil Hadraj"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "שירין מאדי",
    "شيرين ماضي",
    "Shireen Madi"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "קארין קנבורא",
    "كارين قنبورة",
    "Kareen Kanboura"
   ]
  },
  {
   "table": 7,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "סחר סאהר",
    "سحر ساهر",
    "Sahar Saher"
   ]
  },
  {
   "table": 7,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "חנאן נגאר",
    "حنان نجار",
    "Hanan Najjar"
   ]
  },
  {
   "table": 7,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "ماريا صادر",
    "מריה סאדר",
    "Maria Sader"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "ודיע חורי",
    "وديع خوري",
    "Wadie Khoury"
   ]
  },
  {
   "table": 7,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "דימא שרוף",
    "ديما شروف",
    "Deema Sharouf"
   ]
  },
  {
   "table": 7,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "מועאד",
    "MOAD",
    "معاذ"
   ]
  },
  {
   "table": 7,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "احمد شيخ",
    "אחמד שיח'",
    "Ahmad Sheikh"
   ]
  },
  {
   "table": 7,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "אסעד קזעורא",
    "اسعد قزعورة",
    "Asaad Kazoura"
   ]
  },
  {
   "table": 7,
   "count": 2,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "מיסם",
    "ميسم",
    "Maisam"
   ]
  },
  {
   "table": 8,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "רנדה נחאס",
    "رندة نحاس",
    "Randa Nahas"
   ]
  },
  {
   "table": 8,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "גברא נחאס",
    "جبرا نحاس",
    "Jabra Nahas"
   ]
  },
  {
   "table": 8,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "טוני נחאס",
    "طوني نحاس",
    "Tony Nahas"
   ]
  },
  {
   "table": 8,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אמיר דבאג",
    "امير دباغ",
    "Amir Dabbagh"
   ]
  },
  {
   "table": 8,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "נביל דבאג",
    "نبيل دباغ",
    "Nabil Dabbagh"
   ]
  },
  {
   "table": 8,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "גורג דבאג",
    "جورج دباغ",
    "George Dabbagh"
   ]
  },
  {
   "table": 8,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "טארק מור",
    "طارق مور",
    "Tarek Mor"
   ]
  },
  {
   "table": 8,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "רינה נעמה",
    "رينا نعمة",
    "Rina Naameh"
   ]
  },
  {
   "table": 8,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "טרז דבאג",
    "تريز دباغ",
    "Therese Dabbagh"
   ]
  },
  {
   "table": 8,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "נואל דבאג",
    "نويل دباغ",
    "Noel Dabbagh"
   ]
  },
  {
   "table": 8,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "מטאנס זקנון",
    "مطانس زكنون",
    "Mtanes Zaknoun"
   ]
  },
  {
   "table": 8,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "טוני גוליאנוס",
    "طوني جوليانوس",
    "Tony Julianos"
   ]
  },
  {
   "table": 8,
   "count": 2,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "תופיק גבריס",
    "توفيق جبريس",
    "Toufic Jabris"
   ]
  },
  {
   "table": 8,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "וירה נחאס",
    "فيرا نحاس",
    "Vera Nahas"
   ]
  },
  {
   "table": 9,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "بول عيسى",
    "פול עיסא",
    "Paul Issa"
   ]
  },
  {
   "table": 9,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الياس هندومي عيسى",
    "אליאס הנדומי עיסא",
    "Elias Hindoumi Issa"
   ]
  },
  {
   "table": 9,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "فادي فكتور عيسى",
    "פאדי ויקטור עיסא",
    "Fadi Victor Issa"
   ]
  },
  {
   "table": 9,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "فيكتور عيسى",
    "ויקטור עיסא",
    "Victor Issa"
   ]
  },
  {
   "table": 9,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ماتيو عيسى",
    "מתיו עיסא",
    "Matteo Issa"
   ]
  },
  {
   "table": 9,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مارون وايناس عيسى",
    "מארון ואינאס עיסא",
    "Maroun & Inas Issa"
   ]
  },
  {
   "table": 9,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "هند وربيع عليمي",
    "הינד ורביע עלימי",
    "Hind & Rabia Alimi"
   ]
  },
  {
   "table": 9,
   "count": 5,
   "status": "ok",
   "planned": 5,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "انيس عيسى",
    "אניס עיסא",
    "Anis Issa"
   ]
  },
  {
   "table": 9,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "منير سليمان",
    "מוניר סלימאן",
    "Munir Suleiman"
   ]
  },
  {
   "table": 9,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جريس ضو",
    "ג'ריס דאו",
    "Jeries Daw"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "محمود فضل",
    "מחמוד פדל",
    "Mahmoud Fadel"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "مريانا نازي",
    "מריאנה נאזי",
    "Mariana Nazi"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "نمير نجمي",
    "נמיר נג'מי",
    "Namir Najmi"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "دونيا جمال",
    "דוניא ג'מאל",
    "Donia Jamal"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "يارا ايوب",
    "יארא איוב",
    "Yara Ayoub"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "علي عواد",
    "עלי עוואד",
    "Ali Awad"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "امير عسليه",
    "אמיר עסליה",
    "Amir Asaliyeh"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "نور المصري",
    "נור אלמסרי",
    "Nour Al-Masri"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "يوهان بانويان",
    "יוהאן באנויאן",
    "Yohan Banoyan"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "فادي مروشي",
    "FADI MARROUSHI",
    "פאדי מרושי"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "هاروت اركيليانو",
    "הארות ארקיליאנו",
    "Harout Arkeliano"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "وائل قاسم",
    "ואאל קאסם",
    "Wael Kassem"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "احمد زهره (سوبر مايك)",
    "אחמד זהרה (סופר מייק)",
    "Ahmad Zahra (Super Mike)"
   ]
  },
  {
   "table": 10,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "زيكو طجطج",
    "זיקו טג'טג'",
    "Ziko Tajtaj"
   ]
  },
  {
   "table": 10,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "راني ابو الرحمون",
    "ראני אבו אלרחמון",
    "Rani Abu Al-Rahmoun"
   ]
  },
  {
   "table": 10,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "احمد ناشف",
    "Ahmad nashef",
    "אחמד נאשף"
   ]
  },
  {
   "table": 10,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "بيان شقير",
    "ביאן שקיר",
    "Bayan Shkeir"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "איא חרזאן",
    "اية حرزان",
    "Aya Harzan"
   ]
  },
  {
   "table": 10,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "גוני מלשי",
    "جوني ملشي",
    "Johnny Malshi"
   ]
  },
  {
   "table": 11,
   "count": 5,
   "status": "ok",
   "planned": 5,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الياس عزيز عيسى",
    "אליאס עזיז עיסא",
    "Elias Aziz Issa"
   ]
  },
  {
   "table": 11,
   "count": 5,
   "status": "ok",
   "planned": 5,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "نعمه عزيز عيسى",
    "נעמה עזיז עיסא",
    "Neameh Aziz Issa"
   ]
  },
  {
   "table": 11,
   "count": 5,
   "status": "ok",
   "planned": 5,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جوسلين وشربل مطانس",
    "ג'וסלין ושרבל מטאנס",
    "Josline & Charbel Mtanes"
   ]
  },
  {
   "table": 11,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "لويزا ابراهيم",
    "לואיזה אברהים",
    "Louisa Ibrahim"
   ]
  },
  {
   "table": 11,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ايليا بطحيش",
    "איליה בטחיש",
    "Elia Batheesh"
   ]
  },
  {
   "table": 11,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "روزيت وفكري بطحيش",
    "רוזית ופכרי בטחיש",
    "Rosette & Fikri Batheesh"
   ]
  },
  {
   "table": 11,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ميشيل ابراهيم",
    "מישל אברהים",
    "Michel Ibrahim"
   ]
  },
  {
   "table": 12,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "ساندرا بركات",
    "סנדרה ברכאת",
    "Sandra Barakat"
   ]
  },
  {
   "table": 12,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "روكسان بركات",
    "רוקסן ברכאת",
    "Roxanne Barakat"
   ]
  },
  {
   "table": 12,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "גסאן חקעובה",
    "غسان حقعوبة",
    "Ghassan Haqouba"
   ]
  },
  {
   "table": 12,
   "count": 4,
   "status": "ok",
   "planned": 4,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "עבדו בדארנה",
    "عبدو بدارنة",
    "Abdo Badarneh"
   ]
  },
  {
   "table": 12,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "חלים טנוס",
    "حليم طنوس",
    "Halim Tannous"
   ]
  },
  {
   "table": 12,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "פואד טנוס",
    "فؤاد طنوس",
    "Fouad Tannous"
   ]
  },
  {
   "table": 12,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "רמי כסאברי",
    "رامي كسابري",
    "Rami Kassabri"
   ]
  },
  {
   "table": 12,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "וסים חורי",
    "وسيم خوري",
    "Wasim Khoury"
   ]
  },
  {
   "table": 12,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "כמאל ניקולה",
    "كمال نقولا",
    "Kamal Nicola"
   ]
  },
  {
   "table": 12,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "גריס גומעא",
    "جريس جمعة",
    "Jeries Jomaa"
   ]
  },
  {
   "table": 13,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "גבי עפארה",
    "جابي عفارة",
    "Gaby Afara"
   ]
  },
  {
   "table": 13,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "מרוות עפארה",
    "مروات عفارة",
    "Marwat Afara"
   ]
  },
  {
   "table": 13,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "סוזאן עפארה",
    "سوزان عفارة",
    "Suzan Afara"
   ]
  },
  {
   "table": 13,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אלכס נעמה",
    "اليكس نعمة",
    "Alex Naameh"
   ]
  },
  {
   "table": 13,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "רמי חווא",
    "رامي حوا",
    "Rami Hawa"
   ]
  },
  {
   "table": 13,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "עבדאללה אסחאק",
    "عبدالله اسحق",
    "Abdallah Ishak"
   ]
  },
  {
   "table": 14,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اديب عقل",
    "אדיב עקל",
    "Adib Akel"
   ]
  },
  {
   "table": 14,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "امطانس عقل",
    "אמטאנס עקל",
    "Mtanes Akel"
   ]
  },
  {
   "table": 14,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "بيتر وجوليانا كاردو",
    "פיטר וג'וליאנה קרדו",
    "Peter & Juliana Kardo"
   ]
  },
  {
   "table": 14,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "فادي وروزانا عقل",
    "פאדי ורוזנה עקל",
    "Fadi & Rozana Akel"
   ]
  },
  {
   "table": 14,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "شربل عبود",
    "שרבל עבוד",
    "Charbel Abboud"
   ]
  },
  {
   "table": 14,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اسمهان عبود",
    "אסמהאן עבוד",
    "Asmahan Abboud"
   ]
  },
  {
   "table": 14,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جوني جبران",
    "ג'וני ג'ובראן",
    "Johnny Jubran"
   ]
  },
  {
   "table": 14,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الفيرا ومارون عقل",
    "אלווירה ומארון עקל",
    "Elvira & Maroun Akel"
   ]
  },
  {
   "table": 16,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "רפיק סליבא",
    "رفيق صليبا",
    "Rafik Saliba"
   ]
  },
  {
   "table": 16,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "מרואן אבו חדרה",
    "مروان ابو حضرة",
    "Marwan Abu Hadra"
   ]
  },
  {
   "table": 16,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "כמאל גרגורה",
    "كمال جرجورة",
    "Kamal Jarjoura"
   ]
  },
  {
   "table": 16,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "סמי נאסר",
    "سامي ناصر",
    "Sami Nasser"
   ]
  },
  {
   "table": 16,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "חליל אבו חדרה",
    "خليل ابو حضرة",
    "Khalil Abu Hadra"
   ]
  },
  {
   "table": 16,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "וליד נגאר",
    "وليد نجار",
    "Walid Najjar"
   ]
  },
  {
   "table": 17,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "نظيره ونانسي عيسى",
    "נזירה וננסי עיסא",
    "Nazira & Nancy Issa"
   ]
  },
  {
   "table": 17,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "فارس وداليه عيسى",
    "פארס ודליה עיסא",
    "Fares & Dalia Issa"
   ]
  },
  {
   "table": 17,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ليزا وبشاره سوسان",
    "ליזה ובשארה סוסאן",
    "Liza & Bishara Sousan"
   ]
  },
  {
   "table": 17,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "كمال كركبي",
    "כמאל כרכבי",
    "Kamal Karkabi"
   ]
  },
  {
   "table": 17,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ريمون الميشل عيسى",
    "רימון אלמישל עיסא",
    "Raymond Al-Michel Issa"
   ]
  },
  {
   "table": 17,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مارون عجينه",
    "מארון עג'ינה",
    "Maroun Ajineh"
   ]
  },
  {
   "table": 18,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "משפחת הכלה",
   "names": [
    "اسيل",
    "aseel",
    "אסיל"
   ]
  },
  {
   "table": 18,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "חסן אבו גאמע",
    "حسن ابو جامع",
    "Hasan Abu Jamea"
   ]
  },
  {
   "table": 18,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אדם חרבט",
    "ادم حربط",
    "Adam Harbat"
   ]
  },
  {
   "table": 18,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "גלאל חרבט",
    "جلال حربط",
    "Jalal Harbat"
   ]
  },
  {
   "table": 18,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "עלי חרבט",
    "علي حربط",
    "Ali Harbat"
   ]
  },
  {
   "table": 18,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "מיכה בירם",
    "ميخا بيرم",
    "Mikha Biram"
   ]
  },
  {
   "table": 19,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ميشيل وجمانه عيسى",
    "מישל וג'ומאנה עיסא",
    "Michel & Jumana Issa"
   ]
  },
  {
   "table": 19,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جريس وهناء عيسى",
    "ג'ריס והנאא עיסא",
    "Jeries & Hanaa Issa"
   ]
  },
  {
   "table": 19,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ادوار ونجاه جريس",
    "אדואר ונג'אה ג'ריס",
    "Edward & Najah Jeries"
   ]
  },
  {
   "table": 19,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الياس سليمان",
    "אליאס סלימאן",
    "Elias Suleiman"
   ]
  },
  {
   "table": 19,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "امين جماليه",
    "אמין ג'מאליה",
    "Amin Jamalieh"
   ]
  },
  {
   "table": 19,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جريس جماليه",
    "ג'ריס ג'מאליה",
    "Jeries Jamalieh"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "אור דנון",
    "اور دنون",
    "Or Danon"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "אורון רוזנבלט",
    "اورون روزنبلط",
    "Oron Rosenblat"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "איליה רוסושק",
    "ايليا روسوشك",
    "Ilya Rusoshek"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "יאיר דיאמנט",
    "يائير ديامنت",
    "Yair Diamant"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "עידן אראמי",
    "عيدان ارامي",
    "Idan Arami"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "יהודה גארתי",
    "يهودا جارتي",
    "Yehuda Garti"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "סתיו קדוש",
    "ستاف كدوش",
    "Stav Kadosh"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "اشرف ابو اصبع",
    "אשרף אבו אצבע",
    "Ashraf Abu Isba"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "شادي جبران",
    "שאדי ג'ובראן",
    "Shadi Jubran"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "تيريزا زهر",
    "תרזה זהר",
    "Theresa Zahr"
   ]
  },
  {
   "table": 20,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חתן עבודה",
   "names": [
    "ديران طوتونجيان",
    "דיראן טוטונג'יאן",
    "Diran Toutounjian"
   ]
  },
  {
   "table": 21,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "סאמר גבארין",
    "سامر جبارين",
    "Samer Jabareen"
   ]
  },
  {
   "table": 21,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "בדר טבאגה",
    "بدر طباجة",
    "Badr Tabaja"
   ]
  },
  {
   "table": 21,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "ויאאם חגיר",
    "وئام حجير",
    "Weam Hjeir"
   ]
  },
  {
   "table": 21,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "עלאא סאמרי",
    "علاء سامري",
    "Alaa Samri"
   ]
  },
  {
   "table": 21,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "עדנאן אבו כיאס",
    "عدنان ابو كياس",
    "Adnan Abu Kayyas"
   ]
  },
  {
   "table": 21,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "סורור גרוס",
    "سرور جروس",
    "Srour Jarous"
   ]
  },
  {
   "table": 22,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ابراهيم مغزل",
    "אברהים מע'זל",
    "Ibrahim Maghzal"
   ]
  },
  {
   "table": 22,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "امطانس مغزل",
    "אמטאנס מע'זל",
    "Mtanes Maghzal"
   ]
  },
  {
   "table": 22,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "حنا المغزل",
    "חנא אלמע'זל",
    "Hanna Al-Maghzal"
   ]
  },
  {
   "table": 22,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "حني وكمال مغزل",
    "חני וכמאל מע'זל",
    "Hani & Kamal Maghzal"
   ]
  },
  {
   "table": 22,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "يوسف مغزل",
    "יוסף מע'זל",
    "Yousef Maghzal"
   ]
  },
  {
   "table": 22,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مشلين ورائد سليمان",
    "מישלין וראאד סלימאן",
    "Micheline & Raed Suleiman"
   ]
  },
  {
   "table": 22,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "هيلين مغزل",
    "הלן מע'זל",
    "Helen Maghzal"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "אסתי",
    "ESTI",
    "استي"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "ליאור",
    "LIOR",
    "ليئور"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "ליאן",
    "LAYAN",
    "ليان"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "רשא עיסא",
    "رشا عيسى",
    "Rasha Issa"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "שאדין עומרי",
    "شادن عمري",
    "Shaden Omari"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "سندس",
    "SONDOS",
    "סונדוס"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "גבי שוורץ",
    "جابي شوارتس",
    "Gaby Schwartz"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "וליד",
    "WALEED",
    "وليد"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "נדאא",
    "Nedaa",
    "نداء"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "עמרי שורץ",
    "عمري شوارتس",
    "Omri Schwartz"
   ]
  },
  {
   "table": 23,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "באסל סריס",
    "باسل سريس",
    "Basel Saris"
   ]
  },
  {
   "table": 24,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مارون ادوار عيسى",
    "מארון אדואר עיסא",
    "Maroun Edward Issa"
   ]
  },
  {
   "table": 24,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "روني ادوار عيسى",
    "רוני אדואר עיסא",
    "Ronnie Edward Issa"
   ]
  },
  {
   "table": 24,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "رونيت اندراوس",
    "רונית אנדראוס",
    "Ronit Andraos"
   ]
  },
  {
   "table": 24,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "البير ادوار عيسى",
    "אלבר אדואר עיסא",
    "Albert Edward Issa"
   ]
  },
  {
   "table": 24,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الاب عفيف مخول",
    "האב עפיף מח'ול",
    "Father Afif Makhoul"
   ]
  },
  {
   "table": 24,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "حبيب خليل",
    "חביב ח'ליל",
    "Habib Khalil"
   ]
  },
  {
   "table": 24,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "نصيف حجله مخول",
    "נסיף חג'לה מח'ול",
    "Nassif Hajleh Makhoul"
   ]
  },
  {
   "table": 25,
   "count": 0,
   "status": "declined",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "ויליאם גהשאן",
    "وليم جهشان",
    "William Jahshan"
   ]
  },
  {
   "table": 25,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "רביע בתריס",
    "ربيع بتريس",
    "Rabia Batris"
   ]
  },
  {
   "table": 25,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אדוארד אסחאק",
    "ادوارد اسحق",
    "Edward Ishak"
   ]
  },
  {
   "table": 25,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אדוארד חדאד",
    "ادوارد حداد",
    "Edward Haddad"
   ]
  },
  {
   "table": 25,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "ויקטור חוראני",
    "فيكتور حوراني",
    "Victor Hourani"
   ]
  },
  {
   "table": 25,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "דאוד חוראני",
    "داود حوراني",
    "Daoud Hourani"
   ]
  },
  {
   "table": 26,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "شادي مطانس",
    "שאדי מטאנס",
    "Shadi Mtanes"
   ]
  },
  {
   "table": 26,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اديب خليف",
    "אדיב ח'ליף",
    "Adib Khlief"
   ]
  },
  {
   "table": 26,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ديب وريما مارون",
    "דיב ורימה מארון",
    "Dib & Rima Maroun"
   ]
  },
  {
   "table": 26,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الياس فواد جريس",
    "אליאס פואד ג'ריס",
    "Elias Fouad Jeries"
   ]
  },
  {
   "table": 26,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "شكري واميره يعقوب",
    "שוכרי ואמירה יעקוב",
    "Shukri & Amira Yacoub"
   ]
  },
  {
   "table": 26,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مجيد جريس",
    "מג'יד ג'ריס",
    "Majid Jeries"
   ]
  },
  {
   "table": 27,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "אוסאמה כיאט",
    "اسامة خياط",
    "Osama Khayat"
   ]
  },
  {
   "table": 27,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "תאמר חיאללה",
    "تامر خيرالله",
    "Tamer Kheiralla",
    "תאמר חיראללה"
   ]
  },
  {
   "table": 27,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "פארס פארס",
    "فارس فارس",
    "Fares Fares"
   ]
  },
  {
   "table": 27,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "איוב בולס",
    "ايوب بولس",
    "Ayoub Boulos"
   ]
  },
  {
   "table": 27,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "מאהר חיראללה",
    "maher kheiralla",
    "ماهر خيرالله"
   ]
  },
  {
   "table": 27,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "מאהר ורים סול",
    "ماهر وريم سول",
    "Maher & Reem Soul"
   ]
  },
  {
   "table": 27,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Carla",
   "group": "מוזמני הורי הכלה",
   "names": [
    "לואי באש",
    "لؤي باش",
    "Loai Bash"
   ]
  },
  {
   "table": 28,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "جان وجيهان خوري",
    "ג'אן וג'יהאן ח'ורי",
    "Jan & Jihan Khoury"
   ]
  },
  {
   "table": 28,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "لويس شبلي عيسى",
    "לואיס שיבלי עיסא",
    "Louis Shibli Issa"
   ]
  },
  {
   "table": 28,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "لبنى وبولص عيسى",
    "לובנא ובולוס עיסא",
    "Lubna & Boulos Issa"
   ]
  },
  {
   "table": 28,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "مارون شبلي عيسى",
    "מארון שיבלי עיסא",
    "Maroun Shibli Issa"
   ]
  },
  {
   "table": 28,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "بيير ورنين عيسى",
    "פייר ורנין עיסא",
    "Pierre & Ranin Issa"
   ]
  },
  {
   "table": 28,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "نورمان عيسى",
    "נורמן עיסא",
    "Norman Issa"
   ]
  },
  {
   "table": 28,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "سمير شنان",
    "סמיר שנאן",
    "Samir Shanan"
   ]
  },
  {
   "table": 29,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "يوسف دلال",
    "יוסף דלאל",
    "Yousef Dalal"
   ]
  },
  {
   "table": 29,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "عنان الباش",
    "ענאן אלבאש",
    "Anan Al-Bash"
   ]
  },
  {
   "table": 29,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "رامي حوا",
    "רמי חווא",
    "Rami Hawa"
   ]
  },
  {
   "table": 29,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "داهود هلون",
    "דאהוד הלון",
    "Dahoud Hloun"
   ]
  },
  {
   "table": 29,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "حمودي ابو طرس",
    "חמודי אבו טרס",
    "Hamoudi Abu Tars"
   ]
  },
  {
   "table": 29,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "جابي قط",
    "גאבי קט",
    "Gaby Qat"
   ]
  },
  {
   "table": 29,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "جابي زهر",
    "גאבי זהר",
    "Gaby Zahr"
   ]
  },
  {
   "table": 29,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "חברים חתן",
   "names": [
    "امين هلون",
    "אמין הלון",
    "Amin Hloun"
   ]
  },
  {
   "table": 30,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اسامه شقور",
    "אוסאמה שקור",
    "Osama Shakour"
   ]
  },
  {
   "table": 30,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "ايلي شقور",
    "אלי שקור",
    "Eli Shakour"
   ]
  },
  {
   "table": 30,
   "count": 1,
   "status": "ok",
   "planned": 1,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "اسعد شقور",
    "אסעד שקור",
    "Asaad Shakour"
   ]
  },
  {
   "table": 30,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الياس خليل شقور",
    "אליאס ח'ליל שקור",
    "Elias Khalil Shakour"
   ]
  },
  {
   "table": 30,
   "count": 2,
   "status": "ok",
   "planned": 2,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الياس امطانس",
    "אליאס אמטאנס",
    "Elias Mtanes"
   ]
  },
  {
   "table": 30,
   "count": 3,
   "status": "ok",
   "planned": 3,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "الاخويه",
    "האחווה",
    "Al-Akhawiya"
   ]
  },
  {
   "table": null,
   "count": 1,
   "status": "ok",
   "planned": 0,
   "side": "Carla",
   "group": "חברים כלה",
   "names": [
    "האלא",
    "هالة",
    "Hala"
   ]
  },
  {
   "table": null,
   "count": 1,
   "status": "ok",
   "planned": 0,
   "side": "Charlie",
   "group": "מוזמני הורי החתן",
   "names": [
    "هندومي عيسى",
    "הנדומי עיסא",
    "Hindoumi Issa"
   ]
  }
 ]
};
var SEATING = (function (R) {
  var tables = [], byId = {};
  for (var id = 1; id <= 31; id++) {
    var t = { id: id, shape: id <= 12 ? 'rect' : 'round', capacity: id <= 12 ? 24 : 12, sides: [], groups: [], hasList: false };
    tables.push(t); byId[id] = t;
  }
  var sideCount = {};
  R.guests.forEach(function (g) {
    var t = byId[g.table]; if (!t) return;
    t.hasList = true;
    sideCount[t.id] = sideCount[t.id] || {};
    sideCount[t.id][g.side] = (sideCount[t.id][g.side] || 0) + Math.max(g.count, 1);
    if (t.groups.indexOf(g.group) < 0) t.groups.push(g.group);
  });
  tables.forEach(function (t) {
    var sc = sideCount[t.id] || {};
    t.sides = Object.keys(sc).sort(function (a, b) { return sc[b] - sc[a]; });
  });
  return { tables: tables, guests: R.guests, sides: R.sides, groups: R.groups };
})(SEATING_RAW);
if (typeof module !== 'undefined') module.exports = SEATING;
