#!/usr/bin/env python3
"""
Build data.js from the two mit4mit exports.

  python3 tools/build_data.py [invitees.csv] [seating.csv]

Defaults: source/invitees.csv and source/seating.csv.

- invitees.csv  (מוזמנים export): name, side, group and the confirmed
  count "אורחים שאישרו". Phone numbers, if present, are ignored and never
  written to data.js.
- seating.csv   (סידורי הושבה export): which table each guest sits at.

The count shown for every guest is the CONFIRMED count from invitees.csv.
Other-language spellings come from aliases.json (keyed by normalized name).
The script stops with an error if a seated name has no invitee row.
"""
import csv, json, os, re, sys
from collections import OrderedDict, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
INV = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "source", "invitees.csv")
SEAT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "source", "seating.csv")

GROUPS = {
    "חברים כלה": {"he": "חברים כלה", "ar": "أصدقاء العروس", "en": "Bride's friends"},
    "מוזמני הורי הכלה": {"he": "מוזמני הורי הכלה", "ar": "ضيوف أهل العروس", "en": "Bride's parents' guests"},
    "משפחת הכלה": {"he": "משפחת הכלה", "ar": "عائلة العروس", "en": "Bride's family"},
    "מוזמני הורי החתן": {"he": "מוזמני הורי החתן", "ar": "ضيوف أهل العريس", "en": "Groom's parents' guests"},
    "חברים חתן": {"he": "חברים חתן", "ar": "أصدقاء العريس", "en": "Groom's friends"},
    "חתן עבודה": {"he": "חתן - עבודה", "ar": "زملاء عمل العريس", "en": "Groom's work"},
}
SIDES = {
    "Carla": {"he": "קרלה", "ar": "كارلا", "en": "Carla"},
    "Charlie": {"he": "צ'רלי", "ar": "تشارلي", "en": "Charlie"},
}


def norm(s):
    s = s.strip()
    s = re.sub(r"[׳'`’\"]", "", s)
    s = re.sub(r"[()\)/\-.]", " ", s)
    return re.sub(r"\s+", " ", s).strip().lower()


def clean(s):
    return re.sub(r"\s+", " ", s).strip()


def col(row, *names):
    for n in names:
        if n in row:
            return row[n]
    raise KeyError(names)


# ---------- invitees ----------
invitees = OrderedDict()
with open(INV, encoding="utf-8-sig") as f:
    for r in csv.DictReader(f):
        name = col(r, "שם", "name")
        if not name.strip():
            continue
        conf = col(r, "אורחים שאישרו", "confirmed").strip()
        k = norm(name)
        if k in invitees:
            sys.exit("Duplicate invitee name: " + name)
        invitees[k] = {
            "name": clean(name),
            "side": col(r, "צד", "side").strip(),
            "group": col(r, "קבוצה", "group").strip(),
            "confirmed": int(conf) if conf else None,
        }

# ---------- seating ----------
seated = []
tables_in_file = OrderedDict()
table = None
with open(SEAT, encoding="utf-8-sig") as f:
    rows = list(csv.reader(f))
for r in rows:
    r = r + [""] * (6 - len(r))
    if r[0].strip().isdigit():
        table = int(r[0])
        tables_in_file[table] = r[4].strip()
    elif table is not None and r[2].strip():
        k = norm(r[2])
        if k not in invitees:
            sys.exit("Seated guest not found in invitees file: " + r[2])
        seated.append({"table": table, "key": k, "planned": int(r[3] or 0)})

seen = set()
for s in seated:
    if s["key"] in seen:
        sys.exit("Guest seated twice: " + invitees[s["key"]]["name"])
    seen.add(s["key"])

aliases = json.load(open(os.path.join(ROOT, "aliases.json"), encoding="utf-8"))

guests, missing_alias = [], []


def guest(k, table, planned):
    inv = invitees[k]
    alts = aliases.get(k)
    if alts is None:
        missing_alias.append(inv["name"])
        alts = []
    c = inv["confirmed"]
    return OrderedDict([
        ("table", table),
        ("count", c if c is not None else 0),
        ("status", "unknown" if c is None else ("declined" if c == 0 else "ok")),
        ("planned", planned),
        ("side", inv["side"]),
        ("group", inv["group"]),
        ("names", [inv["name"]] + alts),
    ])


for s in seated:
    guests.append(guest(s["key"], s["table"], s["planned"]))
# confirmed guests with no table
for k, inv in invitees.items():
    if k not in seen and (inv["confirmed"] or 0) > 0:
        guests.append(guest(k, None, 0))

out = OrderedDict([
    ("groups", GROUPS),
    ("sides", SIDES),
    ("tablesInFile", list(tables_in_file.keys())),
    ("guests", guests),
])

js = ("/* GENERATED by tools/build_data.py from the mit4mit exports. Do not edit by hand. */\n"
      "var SEATING_RAW = " + json.dumps(out, ensure_ascii=False, indent=1) + ";\n"
      "var SEATING = (function (R) {\n"
      "  var tables = [], byId = {};\n"
      "  for (var id = 1; id <= 31; id++) {\n"
      "    var t = { id: id, shape: id <= 12 ? 'rect' : 'round', capacity: id <= 12 ? 24 : 12, sides: [], groups: [], hasList: false };\n"
      "    tables.push(t); byId[id] = t;\n"
      "  }\n"
      "  var sideCount = {};\n"
      "  R.guests.forEach(function (g) {\n"
      "    var t = byId[g.table]; if (!t) return;\n"
      "    t.hasList = true;\n"
      "    sideCount[t.id] = sideCount[t.id] || {};\n"
      "    sideCount[t.id][g.side] = (sideCount[t.id][g.side] || 0) + Math.max(g.count, 1);\n"
      "    if (t.groups.indexOf(g.group) < 0) t.groups.push(g.group);\n"
      "  });\n"
      "  tables.forEach(function (t) {\n"
      "    var sc = sideCount[t.id] || {};\n"
      "    t.sides = Object.keys(sc).sort(function (a, b) { return sc[b] - sc[a]; });\n"
      "  });\n"
      "  return { tables: tables, guests: R.guests, sides: R.sides, groups: R.groups };\n"
      "})(SEATING_RAW);\n"
      "if (typeof module !== 'undefined') module.exports = SEATING;\n")
open(os.path.join(ROOT, "data.js"), "w", encoding="utf-8").write(js)

# ---------- report ----------
per = defaultdict(int)
for g in guests:
    if g["table"]:
        per[g["table"]] += g["count"]
print("Wrote data.js: %d seated parties, %d confirmed people seated" % (len(seated), sum(per.values())))
unseated = [g for g in guests if g["table"] is None]
if unseated:
    print("Confirmed but no table:", ", ".join("%s (%d)" % (g["names"][0], g["count"]) for g in unseated))
for g in guests:
    if g["table"] and g["status"] != "ok":
        print("Seated but %s: %s (table %d)" % (g["status"], g["names"][0], g["table"]))
    if g["table"] and g["status"] == "ok" and g["count"] != g["planned"]:
        print("Confirmed %d but seating file reserved %d: %s (table %d)" % (g["count"], g["planned"], g["names"][0], g["table"]))
for t in range(1, 32):
    cap = 24 if t <= 12 else 12
    if per[t] > cap:
        print("Table %d over capacity: %d / %d" % (t, per[t], cap))
if missing_alias:
    print("WARNING: no other-language spellings in aliases.json for:", ", ".join(missing_alias))
